<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <Authors>Datalust Pty Ltd and Contributors</Authors>
    <Description>Apache log4net appender for .NET Framework and .NET Standard/Core that writes to the Seq log server over HTTP.</Description>
    <PackageIconUrl>https://datalust.co/images/nuget/seq-client-log4net.png</PackageIconUrl>
    <PackageTags>seq log4net structured logging events</PackageTags>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RootNamespace>Seq</RootNamespace>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
    <PackageTags>seq;log4net</PackageTags>
    <PackageProjectUrl>https://github.com/datalust/seq-client-log4net</PackageProjectUrl>
    <RepositoryUrl>https://github.com/datalust/seq-client-log4net.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <AssemblyOriginatorKeyFile>..\..\asset\Seq.Client-Public.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\asset\Seq.Client-Public.snk" Link="Seq.Client-Public.snk" />
  </ItemGroup>
</Project>
